ARG sourceimage=HuangTraderorg/HuangTrader
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt /HuangTrader/

RUN pip install -r requirements-freqai.txt --user --no-cache-dir
